name: Elixir CI

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: master
        otp-version: 23.0-rc2
    - name: Install Dependencies
      run: mix deps.get
    - name: Run npm audit
      run: npm audit --prefix=apps/fishtank_web/assets
    - name: Run Tests
      run: mix test
